# Docker
# Build and push multiple images to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'cf4a6d48-507b-49df-8f11-f21684310fa1'
  containerRegistry: 'containerregistrybogdaniamnitchi30641.azurecr.io'
  tag: '$(Build.BuildId)'

  agentPoolName: 'local'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: $(agentPoolName)
    steps:
    - task: Docker@2
      displayName: Build and push frontend image
      inputs:
        command: buildAndPush
        repository: 'frontend'
        dockerfile: '$(Build.SourcesDirectory)/energy-app-ui/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          latest
#
    - task: Docker@2
      displayName: Build and push Keycloak image
      inputs:
        command: buildAndPush
        repository: 'keycloak'
        dockerfile: '$(Build.SourcesDirectory)/docker/keycloak/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: 24.0.2

    - task: Docker@2
      displayName: Build and push mysql image
      inputs:
        command: buildAndPush
        repository: 'mysql'
        dockerfile: '$(Build.SourcesDirectory)/docker/mysql/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: 5.7

    - task: Docker@2
      displayName: Build and push user microservice image
      inputs:
        command: buildAndPush
        repository: 'user-microservice'
        dockerfile: '$(Build.SourcesDirectory)/energy-app-ws/user-microservice/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          latest

    - task: Docker@2
      displayName: Build and push device microservice image
      inputs:
        command: buildAndPush
        repository: 'device-microservice'
        dockerfile: '$(Build.SourcesDirectory)/energy-app-ws/device-microservice/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          latest
  
  
