services:
  frontend:
    container_name: frontend
    ports:
      - "4200:4200"
    build:
      context: ./energy-app-ui
      dockerfile: ./Dockerfile
    networks:
      energy-app-network:
        ipv4_address: 172.16.1.2
    extra_hosts:
      - "keycloak-containergroup.germanywestcentral.azurecontainer.io:172.16.1.3"
    depends_on:
      keycloak:
        condition: service_healthy

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "9099:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: "http://keycloak-containergroup.germanywestcentral.azurecontainer.io:8080"
      KEYCLOAK_HOSTNAME: "keycloak-containergroup.germanywestcentral.azurecontainer.io"
    networks:
      energy-app-network:
        ipv4_address: 172.16.1.3
    volumes:
      - ./docker/keycloak/data:/opt/keycloak/data
    command:
      - start-dev
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo > /dev/tcp/localhost/8080" ]
      interval: 10s
      retries: 30
      start_period: 10s
      timeout: 10s

  ums-mysql:
    container_name: ums-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      MYSQL_DATABASE: user_db
      MYSQL_USER: ums_user
      MYSQL_PASSWORD: ums@123
    ports:
      - "3307:3306"
    volumes:
      - ums-mysql:/var/lib/mysql
    networks:
      energy-app-network:
        ipv4_address: 172.16.1.4
    restart: unless-stopped

  user-microservice:
    container_name: user-microservice
    build:
      context: ./energy-app-ws/user-microservice
      dockerfile: ./Dockerfile
    ports:
      - "9081:8081"
    environment:
      - KEYCLOAK_HOST=keycloak-containergroup.germanywestcentral.azurecontainer.io:8080
      - KEYCLOAK_REALM=energy-app
      - DEVICE_HOST=device-containergroup.germanywestcentral.azurecontainer.io:8082
      - DB_IP=ums-mysql
      - DB_PORT=3306
      - DB_USER=ums_user
      - DB_PASSWORD=ums@123
      - DB_DBNAME=user_db
    networks:
      energy-app-network:
        ipv4_address: 172.16.1.5
    extra_hosts:
      - "keycloak-containergroup.germanywestcentral.azurecontainer.io:172.16.1.3"
      - "device-containergroup.germanywestcentral.azurecontainer.io:172.16.1.7"
    depends_on:
      - ums-mysql
    restart: unless-stopped

  dms-mysql:
    container_name: dms-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      MYSQL_DATABASE: device_db
      MYSQL_USER: dms_user
      MYSQL_PASSWORD: dms@123
    ports:
      - "3308:3306"
    volumes:
      - dms-mysql:/var/lib/mysql
    networks:
      energy-app-network:
        ipv4_address: 172.16.1.6
    restart: unless-stopped

  device-microservice:
    container_name: device-microservice
    build:
      context: ./energy-app-ws/device-microservice
      dockerfile: ./Dockerfile
    ports:
      - "9082:8082"
    environment:
      - KEYCLOAK_HOST=keycloak-containergroup.germanywestcentral.azurecontainer.io:8080
      - KEYCLOAK_REALM=energy-app
      - RABBITMQ_HOST=rabbitmq
      - DB_IP=dms-mysql
      - DB_PORT=3306
      - DB_USER=dms_user
      - DB_PASSWORD=dms@123
      - DB_DBNAME=device_db
    networks:
      energy-app-network:
        ipv4_address: 172.16.1.7
    extra_hosts:
      - "keycloak-containergroup.germanywestcentral.azurecontainer.io:172.16.1.3"
    depends_on:
      - dms-mysql
    restart: unless-stopped

networks:
  energy-app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24

volumes:
  ums-mysql:
  dms-mysql:
  mms-mysql:
  mongodb:
  traefik_logs:
