apiVersion: 2019-12-01
location: germanywestcentral
name: keycloak-containergroup
properties:
  containers:
    - name: keycloak
      properties:
        image: containerregistrybogdaniamnitchi30641.azurecr.io/keycloak:24.0.2
        resources:
          requests:
            cpu: 1
            memoryInGb: 1
        environmentVariables:
          - name: KEYCLOAK_ADMIN
            value: admin
          - name: KEYCLOAK_ADMIN_PASSWORD
            value: admin
        ports:
          - port: 8888

  osType: Linux
  ipAddress:
    type: Public
    dnsNameLabel: keycloak-containergroup
    ports:
      - protocol: tcp
        port: 8888
  imageRegistryCredentials:
    - server: containerregistrybogdaniamnitchi30641.azurecr.io
      username: containerregistrybogdaniamnitchi30641
      password: hmrn3b8GzN9lIX23bdks5hv7qAXHpmaGgYW12DoOae+ACRDB7Eap
tags:
  exampleTag: tutorial
type: Microsoft.ContainerInstance/containerGroups
