apiVersion: 2019-12-01
location: germanywestcentral
name: device-containergroup
properties:
  containers:
    - name: dms-mysql
      properties:
        image: containerregistrybogdaniamnitchi30641.azurecr.io/mysql:5.7
        resources:
          requests:
            cpu: 1
            memoryInGb: 1
        environmentVariables:
          - name: MYSQL_ROOT_PASSWORD
            value: admin@123
          - name: MYSQL_DATABASE
            value: device_db
          - name: MYSQL_USER
            value: dms_user
          - name: MYSQL_PASSWORD
            value: dms@123
        ports:
          - port: 3306

    # Device Microservice
    - name: device-microservice
      properties:
        image: containerregistrybogdaniamnitchi30641.azurecr.io/device-microservice:latest
        resources:
          requests:
            cpu: 1
            memoryInGb: 1
        environmentVariables:
          - name: KEYCLOAK_HOST
            value: "keycloak-containergroup.germanywestcentral.azurecontainer.io:8080"
          - name: KEYCLOAK_REALM
            value: "energy-app"
          - name: DB_IP
            value: "localhost"
          - name: DB_PORT
            value: "3306"
          - name: DB_USER
            value: "dms_user"
          - name: DB_PASSWORD
            value: "dms@123"
          - name: DB_DBNAME
            value: "device_db"
        ports:
          - port: 8082

  osType: Linux
  ipAddress:
    type: Public
    dnsNameLabel: device-containergroup
    ports:
      - protocol: tcp
        port: 3306
      - protocol: tcp
        port: 8082
  imageRegistryCredentials:
    - server: containerregistrybogdaniamnitchi30641.azurecr.io
      username: containerregistrybogdaniamnitchi30641
      password: hmrn3b8GzN9lIX23bdks5hv7qAXHpmaGgYW12DoOae+ACRDB7Eap
tags:
  exampleTag: tutorial
type: Microsoft.ContainerInstance/containerGroups
