apiVersion: 2019-12-01
location: germanywestcentral
name: frontend-containergroup
properties:
  containers:
    - name: frontend
      properties:
        image: containerregistrybogdaniamnitchi30641.azurecr.io/frontend:latest
        resources:
          requests:
            cpu: 1
            memoryInGb: 1
        environmentVariables:
          - name: KEYCLOAK_HOST
            value: keycloak
          - name: KEYCLOAK_REALM
            value: energy-app
        ports:
          - port: 4200

  osType: Linux
  ipAddress:
    type: Public
    dnsNameLabel: frontend-containergroup
    ports:
      - protocol: tcp
        port: 4200
  imageRegistryCredentials:
    - server: containerregistrybogdaniamnitchi30641.azurecr.io
      username: containerregistrybogdaniamnitchi30641
      password: hmrn3b8GzN9lIX23bdks5hv7qAXHpmaGgYW12DoOae+ACRDB7Eap
tags:
  exampleTag: tutorial
type: Microsoft.ContainerInstance/containerGroups
